apiVersion: apps/v1
kind: Deployment
metadata:
  name: virt-operator
  namespace: kubevirt
  labels:
    {{- include "kubevirt.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "kubevirt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubevirt.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: kubevirt-operator
      containers:
        - name: operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
