apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kubevirt-cluster-critical
  labels:
    {{- include "kubevirt.labels" . | nindent 4 }}
value: 1000000000
globalDefault: false
description: "This priority class should be used for core kubevirt components only."
