apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevirt-operator
  labels:
    kubevirt.io: ""
    {{- include "kubevirt.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.operator.clusterRole.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubevirt-operator
  namespace: {{ .Values.kubevirt.namespace }}
  labels:
    kubevirt.io: ""
    {{- include "kubevirt.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.operator.role.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-operator
  labels:
    kubevirt.io: ""
    {{- include "kubevirt.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-operator
subjects:
- kind: ServiceAccount
  name: kubevirt-operator
  namespace: {{ .Values.kubevirt.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubevirt-operator-rolebinding
  namespace: {{ .Values.kubevirt.namespace }}
  labels:
    kubevirt.io: ""
    {{- include "kubevirt.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubevirt-operator
subjects:
- kind: ServiceAccount
  name: kubevirt-operator
  namespace: {{ .Values.kubevirt.namespace }}
