# Optional: Enable emulation if hardware virtualization is not available
useEmulation: false
operator:
  image:
    repository: quay.io/kubevirt/virt-operator
    tag: "v1.4.0"
    pullPolicy: IfNotPresent

# Optional: Enable emulation if hardware virtualization is not available
useEmulation: false

# Optional: Configure node placement
nodePlacement:
  nodeSelector: {}
  tolerations: []
