apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.kubevirt.io: ""
  name: kubevirts.kubevirt.io
spec:
  group: kubevirt.io
  names:
    categories:
    - all
    kind: KubeVirt
    plural: kubevirts
    shortNames:
    - kv
    - kvs
    singular: kubevirt
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: KubeVirt represents the object deploying all KubeVirt resources
        properties:
          apiVersion:
            description: APIVersion defines the versioned schema of this representation of an object.
            type: string
          kind:
            description: Kind is a string value representing the REST resource this object represents.
            type: string
          metadata:
            type: object
          spec:
            properties:
              certificateRotateStrategy:
                properties:
                  selfSigned:
                    properties:
                      ca:
                        properties:
                          duration:
                            type: string
                          renewBefore:
                            type: string
                        type: object
                      caOverlapInterval:
                        type: string
                      caRotateInterval:
                        type: string
                      certRotateInterval:
                        type: string
                      server:
                        properties:
                          duration:
                            type: string
                          renewBefore:
                            type: string
                        type: object
                    type: object
                type: object
              configuration:
                properties:
                  developerConfiguration:
                    properties:
                      featureGates:
                        items:
                          type: string
                        type: array
                    type: object
                type: object
              customizeComponents: 
                type: object
              imagePullPolicy:
                type: string
              workloadUpdateStrategy:
                type: object
            type: object
          status:
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
